title: "Inpainting over the cracks: challenges of applying pre-merger searches for massive black hole binaries to realistic LISA datasets"
logo: https://course-module-catalog.port.ac.uk/assets/img/UoP_Master_Logo_Stacked_CMYK.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns:
    - estimate_psds/characteristic_strain.ipynb
    - estimate_psds/plot_psds.ipynb
    - search/overlap_runs/plot_optimal_snr_fitting_factor.ipynb

exclude_patterns:
  - ".venv"
  - ".github"
  - "_build"
  - "Thumbs.db"
  - ".DS_Store"
  - "**.ipynb_checkpoints"

# This means only stuff in the table of contents
# note that if we have run the 'environment building' instructions, there will be
# a bunch of pycbc repo stuff which we don't need to run
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/icg-gravwaves/lisa_premerger_sangria/
  branch: main 

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

sphinx:
  config:
    nb_execution_timeout: 5000
    # Ensure movie assets are copied to _build/html for gh-pages deployment
    html_extra_path:
      - inpainting/inpainting_movie
